global:
  scrape_interval: 10s

  external_labels:
    monitor: 'media_search'

scrape_configs:
  - job_name: 'media_search'

    scrape_interval: 10s

    static_configs:
      - targets: ['localhost:8000']